[arm cartesian motion] added rosparams for arm cart and joint velocity limits
b-it-bots/mas_common_robotics pull request #56
Opened 2019-01-28 22:43 UTC by abhishek098

2019-01-29 07:28 UTC, alex-mitrevski requested changes

2019-01-29 07:28 UTC, alex-mitrevski commented on mcr_manipulation/mcr_arm_cartesian_control/CMakeLists.txt
> +	  -O3
Why is this necessary?

2019-01-29 07:28 UTC, alex-mitrevski commented on mcr_manipulation/mcr_arm_cartesian_control/common/include/mcr_arm_cartesian_control/arm_cartesian_control.h
> +    double max_lin_frame_velocitiy = 0.1;  // m/s
There's a typo in the variable name

2019-01-29 09:23 UTC, abhishek098 commented on mcr_manipulation/mcr_arm_cartesian_control/CMakeLists.txt
> +	  -O3
It is not necessary, but optimization will enhance the performance.

2019-01-29 09:25 UTC, abhishekpadalkar commented on mcr_manipulation/mcr_arm_cartesian_control/common/include/mcr_arm_cartesian_control/arm_cartesian_control.h
> +    double max_lin_frame_velocitiy = 0.1;  // m/s
this was copy paste : ). I will change it.

2019-01-29 09:35 UTC, alex-mitrevski commented on mcr_manipulation/mcr_arm_cartesian_control/CMakeLists.txt
> +	  -O3
Then please add a comment about that in the CMakeLists.

2019-01-29 14:49 UTC, argenos commented on mcr_manipulation/mcr_arm_cartesian_control/CMakeLists.txt
> +	  -O3
Agree with this, clarify what it's for and what the -03 means.

2019-01-29 21:00 UTC, abhishek098 commented on mcr_manipulation/mcr_arm_cartesian_control/common/include/mcr_arm_cartesian_control/arm_cartesian_control.h
> +    double max_lin_frame_velocitiy = 0.1;  // m/s
Fixed.

2019-01-29 21:04 UTC, abhishek098 commented on mcr_manipulation/mcr_arm_cartesian_control/CMakeLists.txt
> +	  -O3
Added a short description and possible effects of it. It is highly unlikely that code will crash as -O3 is very standard optimization. For more info https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html

2019-01-30 05:55 UTC, alex-mitrevski commented on mcr_manipulation/mcr_arm_cartesian_control/CMakeLists.txt
> +	  -O3
The explanation was really about someone looking at the CMakeLists in one year and not wondering why the flag was required in this particular package. ;)

2019-01-30 05:56 UTC, alex-mitrevski approved these changes

2019-03-04 03:21 UTC, sthoduka approved these changes

2019-03-04 03:21 UTC, merged